server:
  port: 8091
spring:
  application:
    name: eureka2
eureka:
  instance:
    hostname: backup
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  server:
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 1000
    #开发阶段关闭，确保注册中心剔除不可用实例
    enable-self-preservation: false
