server:
  port: 8093
spring:
  application:
    name: front
#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: group1
#      auto-offset-reset: earliest
eureka:
  client:
    register-with-eureka: false #在默认设置下,该服务注册中心也会将自己作为客户端来尝试注册它自己,设置为false
    fetch-registry: false #不需要去检索服务，设置为 false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    registry-fetch-interval-seconds: 1
  instance:
    #服务续约任务的调用间隔时间 默认30秒  #表示eureka client发送心跳给server端的频率
    lease-renewal-interval-in-seconds: 1
    #服务失效的时间 默认90秒  #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
    lease-expiration-duration-in-seconds: 2
biz:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000