server:
  port: 8094
spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
    registry-fetch-interval-seconds: 1
zuul:
  routes:
    biz:
      path: /api-biz/**
      serviceId: biz
#      url: http://localhost:8092/
#    front:
#      path: /api-front/**
#      serviceId: front
hystrix:
  command:
    scyp-system:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
biz:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule