server:
  port: 8090
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: master
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://backup:8091/eureka/
    #开启健康体检
    healthcheck:
      enabled: true
  server:
    #开发阶段关闭，确保注册中心剔除不可用实例
    enable-self-preservation: false
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 3000
